### PR TITLE
Code Hygiene & Questions

### PR DESCRIPTION
**Pull request by jeremypbeasley**
I've placed comments with `NOTE: ` anywhere I have a question or suggestion.

Overall comments:

- You need a gitignore. 
- *Never*, I repeat *never* keep node_modules in your repo. 
- You need a readme to let people know to install those modules by `npm install`
- What out for proper indentation, trailing spaces or empty lines inconsistently
- Comments in CSS are all caps or not, inconsistency.
- Stylus is only being use to compile. Consider a pure css compiler.
- Remove JS if you're not using it.
- Folder for favicons but nothing inside.

What is `package-lock.json` for?

You're missing an `author` and a few other helpful things in your `package.json` file.

### CODE REVIEW

**Comment by jeremypbeasley** [comment]
If you have any questions about my comments and it's not an obvious delete and fix, highlight the code in this PR and make a comment.

**Comment by jennminerva** [comment]
Re: all the empty lines (including the ones at the bottoms of files), it's just for organizational purposes while I'm writing, because sometimes all the code, especially frequently repeated code with, say differing links or images or some such, can all blur together for me. It was my intention to delete the empty lines prior to the final push. The empty lines at the bottoms of files are for my own viewing comfort because I can't scroll past the end line so that I'm typing in the middle of the screen.

**Comment by jennminerva** [comment]
Package-lock.json was created by homebrew when I ran npm init

**Comment by jennminerva** [comment]
image
How do you mean "less duplicative"?

**Pull request closed without merging**
